# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  CONNECTORS:
    - travelport
    - sb_api_postgres

tasks:
  help:
    desc: Display this help
    cmds:
      - task -l

  travelport-rebuild:
    desc: Setup and run Travelport integration
    cmds:
      - ddn connector introspect travelport
      - ddn model add travelport "*"
      - ddn command add travelport "*"
      - ddn relationship add travelport "*"
      - ddn supergraph build local --log-level DEBUG
      - ddn run docker-start --log-level DEBUG

  weather-rebuild:
    desc: Rebuild weather integration
    cmds:
      - ddn connector introspect weather --log-level DEBUG
      - ddn model add weather "*"
      - ddn command add weather "*"
      - ddn relationship add weather "*"
      - ddn supergraph build local --log-level DEBUG
      - ddn run docker-start --log-level DEBUG

  build:
    desc: Build the supergraph
    cmds:
      - ddn supergraph build local --log-level DEBUG
      - ddn run docker-start --log-level DEBUG

  weather-templates:
    desc: Compile quicktemplate files for the weather service
    dir: app/connector/weather/weather
    cmds:
      - $HOME/go/bin/qtc
    sources:
      - "*.qtpl"
    generates:
      - "*.qtpl.go"

  start:
    desc: Start the application with Docker
    cmds:
      - HASURA_DDN_PAT=$(ddn auth print-pat) PROMPTQL_SECRET_KEY=$(ddn auth print-promptql-secret-key) docker compose -f compose.yaml --env-file .env up --build --pull always
