# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  CONNECTORS:
    - travelport_js
    - sb_api_postgres

tasks:
  help:
    desc: Display this help
    cmds:
      - task -l

  travelport-js-rebuild:
    desc: Setup and run Travelport integration
    cmds:
      - ddn connector introspect travelport_js
      - ddn model add travelport_js "*"
      - ddn command add travelport_js "*"
      - ddn relationship add travelport_js "*"
      - ddn supergraph build local --log-level DEBUG
      - ddn run docker-start --log-level DEBUG

  travelport-go-rebuild:
    desc: Rebuild Travelport Go integration
    cmds:
      - ddn connector introspect travelport_go --log-level DEBUG
      - ddn model add travelport_go "*"
      - ddn command add travelport_go "*"
      - ddn relationship add travelport_go "*"
      - ddn supergraph build local --log-level DEBUG
      - ddn run docker-start --log-level DEBUG

  build:
    desc: Build the supergraph
    cmds:
      - ddn supergraph build local --log-level DEBUG
      - ddn run docker-start --log-level DEBUG

  start:
    desc: Start the application with Docker
    cmds:
      - HASURA_DDN_PAT=$(ddn auth print-pat) PROMPTQL_SECRET_KEY=$(ddn auth print-promptql-secret-key) docker compose -f compose.yaml --env-file .env up --build --pull always
