services:
  app_weather:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_WEATHER_HASURA_SERVICE_TOKEN_SECRET
      MUTATION_CONCURRENCY_LIMIT: $APP_WEATHER_MUTATION_CONCURRENCY_LIMIT
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_WEATHER_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_WEATHER_OTEL_SERVICE_NAME
      QUERY_CONCURRENCY_LIMIT: $APP_WEATHER_QUERY_CONCURRENCY_LIMIT
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 5244:8080
