services:
  app_sb_api_postgres:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.sb_api_postgres
    environment:
      CONNECTION_URI: $APP_SB_API_POSTGRES_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_SB_API_POSTGRES_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_SB_API_POSTGRES_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_SB_API_POSTGRES_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 4984:8080
